extends: default

rules:
  line-length:
    max: 120
    level: warning
  document-start: disable
  truthy:
    check-keys: false

ignore: |
  node_modules/
  .git/
  dist/
  boringtun-boringtun-cli-0.5.2/
  real address generator/
  DNS over HTTPS/
  edge/
