extends: default

rules:
  indentation: 2
  empty-lines: 1
  line-length:
    max: 120
    level: warning
  document-start: disable
  truthy:
    check-keys: false

ignore: |
  node_modules/
  .github/
  .git/
  sub/
  dist/
  edge/
  boringtun-boringtun-cli-0.5.2/
  real address generator/
  DNS over HTTPS/

  extends: default
