name: Build WG Configs

on:
  # schedule:
  #  - cron: '0 * * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-configs:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r edge/requirements.txt

    - name: Run script
      run: python edge/2nd.py

    - name: Commit and push if changed
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add sub/wireguardn
        git diff --quiet && git diff --staged --quiet || (git commit -m "SYNCED at $(date)" && git push)
