name: Pent
on: [push, pull_request, workflow_dispatch]
env:
  NODE_VERSION: "20"
  PYTHON_VERSION: "3.12"
  PRETTIER_VERSION: "3.4.2"

jobs:
  formatting:
    name: Formatting & Linting
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        language: [python, javascript]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: "recursive"
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

      - name: Set up Python
        if: matrix.language == 'python'
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          cache: 'pip'

      - name: Set up Node.js
        if: matrix.language == 'javascript'
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Install Python tools
        if: matrix.language == 'python'
        run: pip install black ruff isort pylint

      - name: Install JavaScript tools
        if: matrix.language == 'javascript'
        run: |
          npm install
          npm init -y
          npm install prettier@${{ env.PRETTIER_VERSION}} npx eslint . 

      - name: Run Formatting and Linting for Python
        if: matrix.language == 'python'
        id: formatting-py
        run: |
          black --check . || black .
          isort --check . || isort .
          ruff check --fix --unsafe-fixes .
          pylint **/*.py --fail-under=7.0 || true
          if [[ -n $(git status --porcelain) ]]; then
            echo "changes=true" >> $GITHUB_OUTPUT
          fi

      - name: Run Formatting and Linting for JavaScript
        if: matrix.language == 'javascript'
        id: formatting-js
        run: |
          ./node_modules/.bin/prettier --write "**/*.{js,json}" --ignore-unknown
          ./node_modules/.bin/eslint . --ext .js,.json --fix || true
          find . -name "*.json" -exec ./node_modules/.bin/jsonlint -q {} \; || true
          if [[ -n $(git status --porcelain) ]]; then
            echo "changes=true" >> $GITHUB_OUTPUT
          fi

      - name: Commit changes
        if: steps.formatting-py.outputs.changes == 'true' || steps.formatting-js.outputs.changes == 'true'
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<eslint@googlegroups.com>"
          git add -A
          git diff --cached --quiet || git commit -m "style: auto-formatting and lint fixes"
          git push
