name: Pent
on: [push, pull_request, workflow_dispatch]
env:
  NODE_VERSION: '20'
  PYTHON_VERSION: '3.12'

jobs:
  formatting:
    name: Formatting & Linting
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        language: [python, javascript]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: "recursive"
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python
        if: matrix.language == 'python'
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}
         # cache: 'pip'

      - name: Set up Node.js
        if: matrix.language == 'javascript'
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
         # cache: 'npm'

      - name: Install Python tools
        if: matrix.language == 'python'
        run: pip install black ruff isort pylint 

      - name: Install JavaScript tools
        if: matrix.language == 'javascript'
        run: npm install

      - name: Run Formatting and Linting for Python
        if: matrix.language == 'python'
        id: formatting-py
        run: |
          black --check . || black .
          isort --check . || isort .
          ruff check --fix --unsafe-fixes .
          pylint **/*.py --fail-under=7.0 || true
          if [[ -n $(git status --porcelain) ]]; then
            echo "changes=true" >> $GITHUB_OUTPUT
          fi

      - name: Run Formatting and Linting for JavaScript
        if: matrix.language == 'javascript'
        id: formatting-js
        run: |
          npm run format
          npm run lint || true
          if [[ -n $(git status --porcelain) ]]; then
            echo "changes=true" >> $GITHUB_OUTPUT
          fi

      - name: Commit changes if any
        if: failure()
        run: |
          git config user.name "actions-user"
          git config user.email "actions-user@example.com"
          git add -A
          git diff --quiet && git diff --staged --quiet || git commit -m "style: apply code formatting standards" -m "Applied automatic formatting using Black and Prettier"
        continue-on-error: true
