name: "preproccessor"

on:
  push:
    branches: [ "main" ]
    paths:
      - '**/preprocessor.*'
      - 'sub/*.json'
  schedule: 
    - cron: '0 */3 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    defaults:
      run:
        shell: bash -e {0}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
         fetch-depth: 0           
         submodules: 'recursive' 
         token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        env:
          NODE_VERSION: '20'

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'

      - name: Lets go sweetheart
        run: php edge/preprocessor.php

      - name: Configure Git
        run: |
          git config --local user.name "Diana-Cl"
          git config --local user.email "135276904+Diana-Cl@users.noreply.github.com"
          
      - name: Commit changes with timestamp
        run: |
          git add -A
          git diff --cached --quiet || git commit -m "ⅣⅭ Updated $(TZ='Asia/Tehran' date '+%H:%M:%S')" -m "The list of cloudflare IPs has been updated"
          
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
