name: Preprocessor

on:
  push:
    branches: ['main']
    paths:
      - '**/preprocessor.*'
      - 'sub/*.json'
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        dummy: ['single'] 
    defaults:
      run:
        shell: bash -e {0}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: 'recursive'
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3' 

      - name: Get Composer Cache Directory
        id: composer-cache
        run: |
          echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT
      - uses: actions/cache@v4
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress --no-suggest || exit 1
        if: hashFiles('composer.json') != ''

      - name: Run preprocessor.php
        run: php edge/preprocessor.php || exit 1

      - name: Configure Git
        run: |
          git config --local user.name "BotFather"
          git config --local user.email "BotFatherTelegram@gmail.com"

      - name: Commit changes with timestamp
        run: |
          git add -A
          if ! git diff --cached --quiet; then
            git commit -m "IPs Refreshed at: $(TZ='Asia/Tehran' date '+%H:%M:%S')" \
                       -m "The list of Cloudflare IPs has been updated" \
                       --author="Diana-Cl <135276904+Diana-Cl@users.noreply.github.com>"
          else
            echo "No changes detected. Skipping commit."
          fi

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
