name: Format Code

on:
  push:
    paths:
      - '*.js'
      - '*.json'
      - '*.yml'
      - 'hiddify/*'
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  formatting:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
          
      # This step converts files without extensions to json in the vless/hiddify.
      - name: Rename files without extension to .json
        run: |
          cd hiddify
          for file in *; do
            if [[ -f "$file" && "$file" != *.* ]]; then
              mv "$file" "$file.json"
            fi
          done

      - name: Prettier Action
        uses: creyD/prettier_action@v4.3
        with:
          prettier_options: --write "{**/*.{js,json,yml},hiddify/*.json}" --ignore-unknown
          commit_message: "Apply code formatting"
        continue-on-error: true

      # This step will restore the file names to their original state.
      - name: Restore original filenames
        run: |
          cd hiddify
          for file in *.json; do
            if [[ "$file" != "WarpOnWarp.json" ]]; then
              mv "$file" "${file%.json}"
            fi
          done
