name: Winter

on:
  push:
    paths:
      - '*.js'
      - '*.json'
      - '*.yml'
      - '*.php'
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  formatting:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}

      - name: Prettier Action
        uses: creyD/prettier_action@v4.3
        with:
          prettier_options: --write **/*.{js,json,yml} --ignore-unknown
          commit_message: "Apply code formatting"
        continue-on-error: true
