name: Spring

on:
  push:
    branches: [ "main" ]
    paths:
      - '.github/workflows/spring.yml'
      - 'edge/spring.py'
      - 'edge/assets/*.json'
  schedule: 
    - cron: '0 */3 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

    # Set up Python environment
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
        cache: pip
        architecture: x64

    # Cache Python dependencies
    - name: Cache Python packages
      uses: actions/cache@v4
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('edge/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    # Install dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install ipaddress

    # Run Python script
    - name: Run Spring Script
      run: python edge/spring.py

    # Commit changes
    - name: Commit and push changes
      run: |
        git diff --quiet && git diff --staged --quiet || \
        commit_description: "Generate successfully"
        prettier_version: ${{ env.PRETTIER_VERSION }}
        git_email: "github-actions[bot]@users.noreply.github.com"
        git_name: "github-actions[bot]"
        only_changed: true 
        skip_commit: false  
        env:
         GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        continue-on-error: true

    - name: Commit changes if any
      if: failure()
      run: |
        git config --local user.name "Diana-Cl"
        git config --local user.email "135276904+Diana-Cl@users.noreply.github.com"
        git add *.json
        git diff --quiet && git diff --staged --quiet || git commit -m "all done ✔️" -m "Applied automatic formatting using Black and Prettier"
      continue-on-error: true
        
