name: Summer time

on:
  push:
    branches: [ "main" ]
    paths:
      - 'edge/summer.py'
      - 'sub/*.txt'
  schedule:
    - cron: '0 */12 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-configs:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Fetches all history for all branches and tags
        submodules: 'recursive'  # Fetches submodules if any exist
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
        cache: pip
        architecture: x64
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r edge/requirements.txt
    
    - name: Lets go sweetheart
      run: python edge/summer.py
    
    - name: Commit and push if changed
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
        git add sub/*.txt
        git diff --quiet && git diff --staged --quiet || (git commit -m "SYNCED $(TZ='Asia/Tehran' date '+%H:%M:%S')"
        git push)
